### ISSUE TITLE
Confusing error message about tests with false positives

### ISSUE THREAD

**Issue by jbaileyhandle** [eecs-autograder/ag-website-vue#449]
This error mesage is unclear / confusing:
"Tests with false positives incorrectly reported a bug when run against a correct implementation."
Suggest making it clearer.  Would be happy to help come up with a different message, but I'm not entirely sure what triggers this message.

https://github.com/eecs-autograder/ag-website-vue/blob/f17210895493182c5adbaced4eb819fab93e17fc/src/components/project_view/submission_detail/mutation_suite_result.vue#L122

**Comment by james-perretta** [comment]
Hi @jbaileyhandle, This message comes up in the context of mutation testing. Mutation testing on the autograder works as follows. Let's say that we have a source module called `spam.cpp`:
- Instructors provide a _correct_ implementation and a set of _intentionally buggy_ implementations of `spam.cpp`
- Students submit test cases that check the expected behavior of `spam.cpp` and raise an error (i.e. "report a bug") if incorrect behavior is detected.
- The student test cases are run one at a time on the _correct_ implementation of `spam.cpp`. Since the implementation is correct, any errors reported here are _false positives_, and those tests with false positives are discarded. The message in question is displayed when any of the student's test cases were discarded for this reason.
- The remaining test cases are run on each of the _buggy_ implementations. Any errors reported here are _true positives_ and indicate that the buggy implementation has been exposed.

Does that help clarify things? I don't think the message in question needs a full rewrite, but I'd be open suggestions for wording tweaks. Mutation testing can be a bit tricky to explain, and I'd like to keep things concise (despite those two goals being in conflict with each other).

Thanks!

**Comment by jbaileyhandle** [comment]
Hi @james-perretta,

Thank you for the very prompt response and the detailed explanation.  How about something like this:
"False positive detected:  An error was reported when a student test was run against a correct implementation."

In the current error message, it's not clear that the "false positive" part is actually describing the "bug reported when run against correct implementation" part.  Instead, it sounds like we're intentionally running a test case with a false positive (one negative) against a correct implementation (one positive).  This reports a bug (one negative), but that report was incorrect (one negative).  So, we end up with a triple negative - very confusing to think about.

**Comment by james-perretta** [comment]
@jbaileyhandle I like the way that sounds, so I ran with it a bit. Here's what it would look like in context:
![Screenshot from 2020-12-01 09-11-56](https://user-images.githubusercontent.com/4098992/100751516-6914cc80-33b5-11eb-886c-4d223ea59eaf.png)

**Comment by jbaileyhandle** [comment]
Looks good!
