### ISSUE TITLE
Failure to load and display output

### ISSUE THREAD

**Issue by JunhwanK** [eecs-autograder/ag-website-vue#470]
Error found when submitting a file to the Autograder and clicking to see the test case's output.
Unknown steps to reproduce this error. Only happens to a few test cases in some submission.
Opening it in a different browser or refreshing the page doesn't fix it.

Expect to see the Output box display the same information as the Student Output under Output Diff.

Only after clicking on the test case to see its output, the third error message "TypeError" appears on the console.

![image](https://user-images.githubusercontent.com/35044762/108951440-57d51680-76ab-11eb-937a-10e367b7a65e.png)

**Comment by james-perretta** [comment]
I've been able to reproduce it locally and determine the cause. Axios (the http library I use) is parsing the response as JSON, so when the output only contains whitespace and a number, it returns a number instead of a string. I can fix this by using the same file-response-handling methods that I use in other places.

**Comment by james-perretta** [comment]
@JunhwanK Fixed and deployed

**Comment by JunhwanK** [comment]
Thank you!
